[tool.poetry]
name = "baseprojectfastapi"
version = "0.1.0"
description = ""
authors = ["Guilherme Lima <guilherme.pereira@provafacilnaweb.com.br>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.6"
uvicorn = "^0.32.1"
sqlalchemy = "^2.0.36"
python-semantic-release = "^10.3.1"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
version_files = [
    "src/__version__.py",
    "pyproject.toml:version"
]
[tool.semantic_release]
version_source = "tag"
upload_to_pypi = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


