name: Release

on:
  push:
    branches:
      - release-notes

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install python-semantic-release
      - name: Run semantic release
        run: semantic-release publish

      - name: Deploy to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CUSTOM_DOMAIN: 'provafacildocs.github.io'
            CONFIG_FILE: './mkdocs.yml'
            EXTRA_PACKAGES: build-base

